name: Continuous integration

on:
  push:
    branches:
      - develop
      - feature/*
  pull_request:
    branches:
      - develop
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: reto_desarrolladores_php
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306
        options: --health-cmd "mysqladmin ping" --health-interval 10s --health-timeout 5s --health-retries 10


    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.0"
      - uses: actions/checkout@v1
      - name: Validate composer.json and composer.lock
        run: composer validate
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-suggest
      - name: Check code style
        run: composer run-script php-cs-fixer-check
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: composer run-script testdox
        env:
          DB_PASSWORD: root
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
      - name: Execute JS tests via Node
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test
      - name: Fix results PHP coverage files
        run: sed -i -e "s%$GITHUB_WORKSPACE/%%g" *.xml
        working-directory: results
      - name: Fix results JS coverage files
        run: sed -i -e "s%$GITHUB_WORKSPACE/%%g" *.info
        working-directory: results
      - name: Store results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results

  ####################
  # Sonarcloud
  ####################
  reporting:
    needs: laravel-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download results
        uses: actions/download-artifact@v2
        with:
          name: results
          path: results

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
